import { createWebhookLog } from '$lib/server/audit';
import { generatePrSummary } from '$lib/server/ai';
import { getInstallationOctokit } from '$lib/server/github';
import { db } from '$lib/server/db';

export async function handlePullRequestOpened(payload: {
	installation: { id: number };
	repository: { owner: { login: string }; name: string; full_name: string };
	pull_request: {
		number: number;
		title: string;
		body?: string | null;
		html_url: string;
		draft?: boolean;
	};
}) {
	const startedAt = Date.now();
	const installationId = String(payload.installation.id);
	const settings = await db.query.appSettings.findFirst({
		where: (table, { eq }) => eq(table.installationId, installationId)
	});

	if (!settings?.summarizePrs || payload.pull_request.draft) {
		await createWebhookLog({
			installationId,
			eventType: 'pull_request.opened',
			action: 'summary_skipped',
			status: 'skipped',
			repoFullName: payload.repository.full_name,
			resourceNumber: payload.pull_request.number,
			resourceUrl: payload.pull_request.html_url,
			errorMessage: payload.pull_request.draft
				? 'Draft pull request.'
				: 'PR summaries are disabled.',
			durationMs: Date.now() - startedAt
		});
		return;
	}

	const octokit = await getInstallationOctokit(installationId);
	const diffResponse = await octokit.request('GET /repos/{owner}/{repo}/pulls/{pull_number}', {
		owner: payload.repository.owner.login,
		repo: payload.repository.name,
		pull_number: payload.pull_request.number,
		headers: {
			accept: 'application/vnd.github.v3.diff'
		}
	});

	const summary = await generatePrSummary({
		repository: payload.repository.full_name,
		title: payload.pull_request.title,
		body: payload.pull_request.body,
		diff:
			typeof diffResponse.data === 'string' ? diffResponse.data : JSON.stringify(diffResponse.data)
	});

	await octokit.rest.issues.createComment({
		owner: payload.repository.owner.login,
		repo: payload.repository.name,
		issue_number: payload.pull_request.number,
		body: `${summary.summary}\n\n---\nGenerated by RepoMind.`
	});

	await createWebhookLog({
		installationId,
		eventType: 'pull_request.opened',
		action: 'summary_posted',
		status: 'success',
		repoFullName: payload.repository.full_name,
		resourceNumber: payload.pull_request.number,
		resourceUrl: payload.pull_request.html_url,
		aiModel: summary.model,
		tokensUsed: summary.tokensUsed,
		durationMs: Date.now() - startedAt
	});
}
